version: 2

jobs:
  build-and-test:
    steps:
      - checkout
      - run:
          name: Run tests
          command: bundle exec fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: WhatsNew-Example
